"""Módulo core de Jessyca Windows MCP."""

from core.audit_logger import AuditLogEntry, AuditLogger, get_audit_logger
from core.capability import CapabilityManager, ToolCapabilitySpec
from core.confirmation import (
    ConfirmationManager,
    ConfirmationRequest,
    ConfirmationResponse,
    ConfirmationResult,
    ConfirmationStatus,
    IConfirmationProvider,
    MockConfirmationProvider,
    compute_action_fingerprint,
    sanitize_sensitive_parameters,
)
from core.constants import APP_NAME, APP_VERSION
from core.context_manager import ContextItem, ContextManager
from core.contracts import (
    IConfirmationManager,
    IPermissionManager,
    IRiskEvaluator,
    ISecurityEvaluator,
    ISecurityManager,
    IService,
    ITool,
    IToolRegistry,
)
from core.event_bus import (
    Event,
    EventBus,
    EventPriority,
    Subscription,
    get_event_bus,
)
from core.exceptions import (
    ConfigurationError,
    JessycaError,
    MCPError,
    ToolExecutionError,
    ToolNotFoundError,
    ValidationError,
    WindowsPlatformError,
)
from core.executor import (
    PlanExecutionResult,
    RollbackAction,
    TaskExecutionResult,
    TaskExecutor,
)
from core.logger import get_logger, setup_logger
from core.permission_manager import (
    PermissionDecision,
    PermissionManager,
    PermissionRequest,
    PermissionResult,
    PermissionSource,
)
from core.planner import AIPlanner, ExecutionPlan, SubTask
from core.policy_rules import ConfigurablePolicyRule, PolicyManager
from core.risk_engine import (
    BulkOperationRiskRule,
    FileOperationRiskRule,
    IRiskRule,
    PrivilegeRiskRule,
    ProcessControlRiskRule,
    RiskAssessment,
    RiskEngine,
    RiskFactor,
    RiskRule,
    StaticMetadataRiskRule,
    SystemPathRiskRule,
    UnknownOperationRiskRule,
)
from core.security import (
    AuditRecord,
    PermissionAction,
    RiskLevel,
    SecurityDecision,
    SecurityManager,
    SecurityPolicy,
    SecurityStatus,
    ToolSecurityProfile,
    check_hierarchical_permission,
)
from core.security_architecture import (
    BaseSecurityManager,
    SecurityContext,
    SecurityDecisionType,
    SecurityLevel,
    SecurityRequest,
    SecurityResult,
    ToolSecurityMetadata,
)
from core.session_manager import Session, SessionManager, ToolExecutionLog
from core.types import EnvironmentMode, LogLevel, Result, WindowsVersion

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "IService",
    "ITool",
    "IToolRegistry",
    "ISecurityManager",
    "ISecurityEvaluator",
    "IRiskEvaluator",
    "IPermissionManager",
    "IConfirmationManager",
    "IConfirmationProvider",
    "JessycaError",
    "ConfigurationError",
    "WindowsPlatformError",
    "MCPError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ValidationError",
    "get_logger",
    "setup_logger",
    "EnvironmentMode",
    "LogLevel",
    "Result",
    "WindowsVersion",
    "RiskLevel",
    "PermissionAction",
    "SecurityStatus",
    "ToolSecurityProfile",
    "SecurityDecision",
    "SecurityPolicy",
    "check_hierarchical_permission",
    "AuditRecord",
    "SecurityManager",
    "SecurityLevel",
    "SecurityDecisionType",
    "SecurityContext",
    "ToolSecurityMetadata",
    "SecurityRequest",
    "SecurityResult",
    "BaseSecurityManager",
    "RiskFactor",
    "IRiskRule",
    "RiskRule",
    "StaticMetadataRiskRule",
    "PrivilegeRiskRule",
    "SystemPathRiskRule",
    "FileOperationRiskRule",
    "ProcessControlRiskRule",
    "BulkOperationRiskRule",
    "UnknownOperationRiskRule",
    "RiskAssessment",
    "RiskEngine",
    "PermissionDecision",
    "PermissionSource",
    "PermissionRequest",
    "PermissionResult",
    "PermissionManager",
    "ConfirmationStatus",
    "ConfirmationRequest",
    "ConfirmationResponse",
    "ConfirmationResult",
    "ConfirmationManager",
    "MockConfirmationProvider",
    "compute_action_fingerprint",
    "sanitize_sensitive_parameters",
    "AuditLogEntry",
    "AuditLogger",
    "get_audit_logger",
    "ConfigurablePolicyRule",
    "PolicyManager",
    "ToolCapabilitySpec",
    "CapabilityManager",
    "ContextItem",
    "ContextManager",
    "ToolExecutionLog",
    "Session",
    "SessionManager",
    "Event",
    "EventPriority",
    "Subscription",
    "EventBus",
    "get_event_bus",
    "SubTask",
    "ExecutionPlan",
    "AIPlanner",
    "RollbackAction",
    "TaskExecutionResult",
    "PlanExecutionResult",
    "TaskExecutor",
]
