"""Módulo core de Jessyca Windows MCP."""

from core.audit_logger import (
    AuditEvent,
    AuditEventType,
    AuditFailureMode,
    AuditLogEntry,
    AuditLogger,
    FileAuditSink,
    MemoryAuditSink,
    get_audit_logger,
    sanitize_audit_data,
)
from core.autonomy_policy import (
    AutonomousTaskRequest,
    AutonomyConfirmationRequiredError,
    AutonomyEvaluationResult,
    AutonomyPermissionDeniedError,
    AutonomyPolicy,
    AutonomySecurityError,
    ScheduledActionPolicy,
    TaskActionRisk,
    TaskRiskClassifier,
)
from core.builtin_capabilities import (
    get_builtin_capabilities,
    register_builtin_capabilities,
)
from core.capabilities import (
    CapabilityDecision,
    CapabilityOperation,
    CapabilityRiskLevel,
    CapabilitySource,
    CapabilityStatus,
    ToolCapability,
    compute_capability_fingerprint,
)
from core.capability import CapabilityManager, ToolCapabilitySpec
from core.capability_registry import (
    CapabilityRegistry,
    ICapabilityRegistry,
    get_capability_registry,
)
from core.capability_resolver import (
    CapabilityResolution,
    CapabilityResolver,
)
from core.capability_validator import (
    check_and_assert_capability,
    validate_capability,
    validate_operation,
    validate_registry,
)
from core.change_transaction import (
    ChangeResult,
    ChangeSnapshot,
    ChangeTransaction,
    ChangeTransactionManager,
    FakeTransactionProvider,
    IChangeTransactionProvider,
    Reversibility,
    RollbackResult,
    TransactionConfirmationRequiredError,
    TransactionError,
    TransactionRollbackFailedError,
    TransactionState,
    TransactionVerificationError,
)
from core.confirmation import (
    ConfirmationManager,
    ConfirmationRequest,
    ConfirmationResponse,
    ConfirmationResult,
    ConfirmationStatus,
    IConfirmationProvider,
    MockConfirmationProvider,
    compute_action_fingerprint,
    sanitize_sensitive_parameters,
)
from core.constants import APP_NAME, APP_VERSION
from core.context_manager import ContextItem, ContextManager
from core.contracts import (
    IAuditLogger,
    IAuditSink,
    IConfirmationManager,
    IConfirmationProvider,
    IPermissionManager,
    IPolicyEvaluator,
    IPolicyProvider,
    IRiskEvaluator,
    ISecurityEvaluator,
    ISecurityManager,
    IService,
    ITool,
    IToolRegistry,
)
from core.event_bus import (
    Event,
    EventBus,
    EventPriority,
    Subscription,
    get_event_bus,
)
from core.exceptions import (
    ConfigurationError,
    JessycaError,
    MCPError,
    ToolExecutionError,
    ToolNotFoundError,
    ValidationError,
    WindowsPlatformError,
)
from core.executor import (
    PlanExecutionResult,
    RollbackAction,
    TaskExecutionResult,
    TaskExecutor,
)
from core.logger import get_logger, setup_logger
from core.memory_consolidation import (
    ConsolidationReport,
    MemoryCompactionPolicy,
    MemoryRetentionPolicy,
    RetentionDecision,
    SessionConsolidator,
)
from core.notification_dispatcher import (
    NotificationChannel,
    NotificationDispatcher,
    NotificationError,
    NotificationItem,
    NotificationPriority,
    NotificationResult,
    NotificationStatus,
)
from core.permission_manager import (
    PermissionDecision,
    PermissionManager,
    PermissionRequest,
    PermissionResult,
    PermissionSource,
)
from core.planner import AIPlanner, ExecutionPlan, SubTask
from core.plugin_execution_pipeline import (
    PluginExecutionPipeline,
    PluginExecutionPipelineBypassError,
    PluginExecutionPipelineError,
)
from core.plugin_loader import (
    FakePluginLoader,
    IPluginLoader,
    LoadedPlugin,
    PluginCapacityExceededError,
    PluginIntegrityError,
    PluginLoader,
    PluginLoaderSecurityError,
)
from core.plugin_manifest import (
    PluginManifest,
    PluginManifestError,
    PluginManifestValidator,
    PluginMetadata,
    PluginPathSecurityError,
    PluginValidationError,
    PluginVersionError,
)
from core.plugin_sandbox import (
    PluginExecutionResult,
    PluginExecutionSandbox,
    PluginSandboxError,
    PluginSandboxTimeoutError,
    PluginSandboxViolationError,
)
from core.plugin_security import (
    PluginCapability,
    PluginCapabilityViolationError,
    PluginDeclaredCapability,
    PluginPermission,
    PluginPrivilegeElevationError,
    PluginRiskProfile,
    PluginSecurityError,
    PluginSecurityPolicy,
)
from core.policy_rules import ConfigurablePolicyRule, PolicyManager
from core.registry_boundary import (
    RegistryBoundaryError,
    RegistrySecurityViolationError,
    RegistryWriteBoundary,
    RegistryWriteDisabledError,
    RegistryWriteRequest,
)
from core.risk_engine import (
    BulkOperationRiskRule,
    FileOperationRiskRule,
    IRiskRule,
    PrivilegeRiskRule,
    ProcessControlRiskRule,
    RiskAssessment,
    RiskEngine,
    RiskFactor,
    RiskRule,
    StaticMetadataRiskRule,
    SystemPathRiskRule,
    UnknownOperationRiskRule,
)
from core.security import (
    AuditRecord,
    PermissionAction,
    RiskLevel,
    SecurityDecision,
    SecurityManager,
    SecurityPolicy,
    SecurityStatus,
    ToolSecurityProfile,
    check_hierarchical_permission,
)
from core.security_architecture import (
    BaseSecurityManager,
    SecurityContext,
    SecurityDecisionType,
    SecurityLevel,
    SecurityRequest,
    SecurityResult,
    ToolSecurityMetadata,
)
from core.security_policy import (
    DefaultPolicyProvider,
    GenericPolicyRule,
    InvalidPolicyError,
    OperationPolicyRule,
    PathPolicyRule,
    PolicyDecision,
    PolicyRule,
    PolicyRuleBase,
    PolicyRuleCondition,
    PolicySource,
    PrivilegePolicyRule,
    RiskPolicyRule,
    SecurityPolicyEvaluator,
    ToolPolicyRule,
    create_default_security_policy,
    validate_security_policy,
)
from core.semantic_retriever import (
    RelevanceScorer,
    SemanticMemoryResult,
    SemanticMemoryRetriever,
    SemanticMemoryType,
)
from core.service_boundary import (
    ProtectedServiceViolationError,
    ServiceBoundaryError,
    ServiceControlBoundary,
    ServiceControlRequest,
    ServiceWriteDisabledError,
    UnknownServiceError,
)
from core.session_manager import SessionManager
from core.software_boundary import (
    ArbitraryInstallerError,
    PackageAllowlistViolationError,
    PackageIdentityMismatchError,
    SoftwareInstallBoundary,
    SoftwareInstallDisabledError,
    SoftwareInstallError,
    SoftwareInstallRequest,
    UntrustedSourceError,
)
from core.task_scheduler import (
    CronLikeTrigger,
    DirectToolExecutionBypassError,
    EventTrigger,
    IntervalTrigger,
    ITaskTrigger,
    ScheduledTaskDefinition,
    ScheduledTaskManager,
    ScheduledTaskResult,
    SchedulerSecurityError,
)
from core.types import EnvironmentMode, LogLevel, Result, WindowsVersion
from core.wake_word_detector import (
    WakeWordDetector,
    WakeWordDisabledError,
    WakeWordSecurityError,
    WakeWordState,
)

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "CapabilitySource",
    "CapabilityRiskLevel",
    "CapabilityDecision",
    "CapabilityStatus",
    "CapabilityOperation",
    "ToolCapability",
    "compute_capability_fingerprint",
    "ICapabilityRegistry",
    "CapabilityRegistry",
    "get_capability_registry",
    "CapabilityResolution",
    "CapabilityResolver",
    "validate_capability",
    "validate_operation",
    "validate_registry",
    "check_and_assert_capability",
    "get_builtin_capabilities",
    "register_builtin_capabilities",
    "IService",
    "ITool",
    "IToolRegistry",
    "ISecurityManager",
    "ISecurityEvaluator",
    "IRiskEvaluator",
    "IPermissionManager",
    "IPolicyEvaluator",
    "IPolicyProvider",
    "IConfirmationManager",
    "IConfirmationProvider",
    "PolicySource",
    "InvalidPolicyError",
    "PolicyRuleCondition",
    "PolicyRule",
    "PolicyDecision",
    "PolicyRuleBase",
    "ToolPolicyRule",
    "OperationPolicyRule",
    "RiskPolicyRule",
    "PathPolicyRule",
    "PrivilegePolicyRule",
    "GenericPolicyRule",
    "SecurityPolicyEvaluator",
    "validate_security_policy",
    "create_default_security_policy",
    "DefaultPolicyProvider",
    "JessycaError",
    "ConfigurationError",
    "WindowsPlatformError",
    "MCPError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ValidationError",
    "get_logger",
    "setup_logger",
    "EnvironmentMode",
    "LogLevel",
    "Result",
    "WindowsVersion",
    "RiskLevel",
    "PermissionAction",
    "SecurityStatus",
    "ToolSecurityProfile",
    "SecurityDecision",
    "SecurityPolicy",
    "check_hierarchical_permission",
    "AuditRecord",
    "SecurityManager",
    "SecurityLevel",
    "SecurityDecisionType",
    "SecurityContext",
    "ToolSecurityMetadata",
    "SecurityRequest",
    "SecurityResult",
    "BaseSecurityManager",
    "RiskFactor",
    "IRiskRule",
    "RiskRule",
    "StaticMetadataRiskRule",
    "PrivilegeRiskRule",
    "SystemPathRiskRule",
    "FileOperationRiskRule",
    "ProcessControlRiskRule",
    "BulkOperationRiskRule",
    "UnknownOperationRiskRule",
    "RiskAssessment",
    "RiskEngine",
    "PermissionDecision",
    "PermissionSource",
    "PermissionRequest",
    "PermissionResult",
    "PermissionManager",
    "ConfirmationStatus",
    "ConfirmationRequest",
    "ConfirmationResponse",
    "ConfirmationResult",
    "ConfirmationManager",
    "MockConfirmationProvider",
    "compute_action_fingerprint",
    "sanitize_sensitive_parameters",
    "AuditLogEntry",
    "AuditEvent",
    "AuditEventType",
    "AuditFailureMode",
    "AuditLogger",
    "FileAuditSink",
    "MemoryAuditSink",
    "IAuditLogger",
    "IAuditSink",
    "get_audit_logger",
    "sanitize_audit_data",
    "ConfigurablePolicyRule",
    "PolicyManager",
    "ToolCapabilitySpec",
    "CapabilityManager",
    "ContextItem",
    "ContextManager",
    "SessionManager",

    "Event",
    "EventPriority",
    "Subscription",
    "EventBus",
    "get_event_bus",
    "RelevanceScorer",
    "SemanticMemoryType",
    "SemanticMemoryResult",
    "SemanticMemoryRetriever",
    "RetentionDecision",
    "MemoryRetentionPolicy",
    "MemoryCompactionPolicy",
    "SessionConsolidator",
    "ConsolidationReport",
    "AutonomyPolicy",
    "TaskRiskClassifier",
    "ScheduledActionPolicy",
    "TaskActionRisk",
    "AutonomousTaskRequest",
    "AutonomyEvaluationResult",
    "AutonomySecurityError",
    "AutonomyPermissionDeniedError",
    "AutonomyConfirmationRequiredError",
    "ScheduledTaskManager",
    "ITaskTrigger",
    "IntervalTrigger",
    "CronLikeTrigger",
    "EventTrigger",
    "ScheduledTaskDefinition",
    "ScheduledTaskResult",
    "SchedulerSecurityError",
    "DirectToolExecutionBypassError",
    "WakeWordDetector",
    "WakeWordState",
    "WakeWordSecurityError",
    "WakeWordDisabledError",
    "NotificationDispatcher",
    "NotificationItem",
    "NotificationResult",
    "NotificationPriority",
    "NotificationChannel",
    "NotificationStatus",
    "NotificationError",
    "PluginSecurityPolicy",
    "PluginCapability",
    "PluginRiskProfile",
    "PluginPermission",
    "PluginDeclaredCapability",
    "PluginSecurityError",
    "PluginCapabilityViolationError",
    "PluginPrivilegeElevationError",
    "PluginManifest",
    "PluginMetadata",
    "PluginManifestValidator",
    "PluginManifestError",
    "PluginValidationError",
    "PluginPathSecurityError",
    "PluginVersionError",
    "PluginLoader",
    "LoadedPlugin",
    "IPluginLoader",
    "FakePluginLoader",
    "PluginLoaderSecurityError",
    "PluginIntegrityError",
    "PluginCapacityExceededError",
    "PluginExecutionSandbox",
    "PluginExecutionResult",
    "PluginSandboxError",
    "PluginSandboxViolationError",
    "PluginSandboxTimeoutError",
    "PluginExecutionPipeline",
    "PluginExecutionPipelineBypassError",
    "PluginExecutionPipelineError",
    "ChangeTransaction",
    "ChangeSnapshot",
    "ChangeResult",
    "RollbackResult",
    "Reversibility",
    "TransactionState",
    "ChangeTransactionManager",
    "FakeTransactionProvider",
    "IChangeTransactionProvider",
    "TransactionError",
    "TransactionConfirmationRequiredError",
    "TransactionRollbackFailedError",
    "TransactionVerificationError",
    "RegistryWriteBoundary",
    "RegistryWriteRequest",
    "RegistryBoundaryError",
    "RegistryWriteDisabledError",
    "RegistrySecurityViolationError",
    "ServiceControlBoundary",
    "ServiceControlRequest",
    "ServiceBoundaryError",
    "ServiceWriteDisabledError",
    "ProtectedServiceViolationError",
    "UnknownServiceError",
    "SoftwareInstallBoundary",
    "SoftwareInstallRequest",
    "SoftwareInstallError",
    "SoftwareInstallDisabledError",
    "ArbitraryInstallerError",
    "UntrustedSourceError",
    "PackageIdentityMismatchError",
    "PackageAllowlistViolationError",
    "SubTask",














    "ExecutionPlan",
    "AIPlanner",
    "RollbackAction",
    "TaskExecutionResult",
    "PlanExecutionResult",
    "TaskExecutor",
    # User Profile & Personalization (Fase 22)
    "ConsentStatus",
    "InformationScopeType",
    "PreferenceDetector",
    "ProfileCategory",
    "ProfilePreferenceItem",
    "UserProfileManager",
    "UserProfileStore",
    "get_user_profile_manager",
    # Planning Engine (Fase 23)
    "PlanBuilder",
    "PlanExecutor",
    "PlanStatus",
    "PlanStep",
    "PlanStepResult",
    "PlanValidationError",
    "PlanValidator",
    "PlanningEngine",
    "StepStatus",
    "get_planning_engine",
    # Control Center & Observability (Fase 24)
    "ControlCenter",
    "ControlCenterSnapshot",
    "ControlCommandResult",
    "SystemState",
    "get_control_center",
    # Smart Model Routing 2.0 (Fase 25)
    "ModelRoutingDecision",
    "ModelPerformanceTracker",
    # Model Performance Learning (Fase 26)
    "InferenceExecutionRecord",
    "ModelPerformanceStats",
    "ModelPerformanceStore",
    "ModelPerformanceLearner",
    "get_model_performance_learner",
    # Proactive Assistant (Fase 27)
    "ProactiveEventType",
    "ProactiveActionType",
    "ProactiveEvent",
    "ProactivePolicyDecision",
    "ProactiveExecutionResult",
    "ProactivePolicyEngine",
    "ProactiveAssistant",
    "get_proactive_assistant",
    # Plugin Ecosystem 2.0 (Fase 28)
    "PluginStatus",
    "PluginToolDeclaration",
    "PluginManifest2",
    "ValidationStageResult",
    "PluginValidationReport",
    "PluginEcosystemValidator",
    "PluginEcosystemManager",
    "get_plugin_ecosystem_manager",
    # Skill Framework Foundation (Fase 28.0)
    "BaseSkill",
    "SkillCapability",
    "SkillPermission",
    "SkillDefinition",
    "SkillContext",
    "SkillResult",
    "SkillStatus",
    "SkillValidator",
    "SkillRegistry",
    "get_skill_registry",
    "SkillRouter",
    "get_skill_router",
    "SkillRuntime",
    "SkillManager",
    "get_skill_manager",
]

from skills.base_skill import BaseSkill
from skills.skill_models import (
    SkillCapability,
    SkillContext,
    SkillDefinition,
    SkillPermission,
    SkillResult,
    SkillStatus,
)
from skills.skill_validator import (
    SkillValidationError,
    SkillValidator,
)
from skills.skill_registry import (
    SkillRegistry,
    get_skill_registry,
)
from skills.skill_router import (
    SkillRouter,
    get_skill_router,
)
from skills.skill_runtime import (
    SkillRuntime,
)
from skills.skill_manager import (
    SkillManager,
    get_skill_manager,
)

from core.plugins_v2 import (
    PluginEcosystemManager,
    PluginEcosystemValidator,
    PluginManifest2,
    PluginStatus,
    PluginToolDeclaration,
    PluginValidationReport,
    ValidationStageResult,
    get_plugin_ecosystem_manager,
)

from core.proactive import (
    ProactiveActionType,
    ProactiveAssistant,
    ProactiveEvent,
    ProactiveEventType,
    ProactiveExecutionResult,
    ProactivePolicyDecision,
    ProactivePolicyEngine,
    get_proactive_assistant,
)
from core.llm.performance_models import (
    InferenceExecutionRecord,
    ModelPerformanceStats,
)
from core.llm.performance_learning import (
    ModelPerformanceLearner,
    get_model_performance_learner,
)
from core.llm.performance_store import (
    ModelPerformanceStore,
)
from core.llm.smart_routing_models import (
    ModelPerformanceTracker,
    ModelRoutingDecision,
)

from core.observability.control_center import (
    ControlCenter,
    get_control_center,
)
from core.observability.control_center_models import (
    ControlCenterSnapshot,
    ControlCommandResult,
    SystemState,
)
from core.planning import (
    PlanBuilder,
    PlanExecutor,
    PlanStatus,
    PlanStep,
    PlanStepResult,
    PlanValidationError,
    PlanValidator,
    PlanningEngine,
    StepStatus,
    get_planning_engine,
)
from core.profile import (
    ConsentStatus,
    InformationScopeType,
    PreferenceDetector,
    ProfileCategory,
    ProfilePreferenceItem,
    UserProfileManager,
    UserProfileStore,
    get_user_profile_manager,
)

