# Configuración general de Jessyca
system:
  name: "Jessyca"
  version: "0.1.0"
  language: "es-ES"
  debug: false

audio:
  default_voice: "es-PE-CamilaNeural"
  wake_word: "jessyca"
  wake_word_variations:
    - "jessyca"
    - "jessica"
    - "yesica"
    - "yessica"
    - "jesica"
    - "jesika"
    - "yesika"
    - "esica"
    - "sica"
    - "yeca"
  sample_rate: 16000
  channels: 1

logging:
  level: "INFO"
  console_output: true
