"""Dataset de 50 casos de prueba para el Benchmark del Router Inteligente Experimental (tests/router/test_cases.py).

Distribución exacta:
- 10 Fast Interaction
- 10 Technical
- 10 Complex Reasoning
- 10 Agent Planning
- 5 Offline
- 5 Ambiguous
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from core.llm.experimental_router import TaskCategory


@dataclass(frozen=True)
class RouterTestCase:
    """Caso de prueba formal para evaluación del enrutador de modelos."""

    test_id: str
    category: TaskCategory
    prompt: str
    is_voice: bool = False
    is_offline: bool = False
    expected_task_type: TaskCategory = TaskCategory.FAST_INTERACTION
    expected_model_family: str = "gemma"
    acceptable_models: tuple[str, ...] = ("gemma4:e4b",)
    minimum_confidence: float = 0.80
    description: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


ROUTER_BENCHMARK_CASES: tuple[RouterTestCase, ...] = (
    # ── 1. FAST INTERACTION (10 casos) ────────────────────────────────────────
    RouterTestCase(
        test_id="FAST_01",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Hola Jessica, buenos días.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Saludo básico por voz.",
    ),
    RouterTestCase(
        test_id="FAST_02",
        category=TaskCategory.FAST_INTERACTION,
        prompt="¿Qué hora es?",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Consulta directa de reloj.",
    ),
    RouterTestCase(
        test_id="FAST_03",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Jessica, abre el bloc de notas.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Apertura directa de bloc de notas.",
    ),
    RouterTestCase(
        test_id="FAST_04",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Jessica, abre Google.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Navegación directa a Google.",
    ),
    RouterTestCase(
        test_id="FAST_05",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Jessica, cierra Google.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Cierre directo de ventana.",
    ),
    RouterTestCase(
        test_id="FAST_06",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Sube el volumen un poco.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Control de audio rápido.",
    ),
    RouterTestCase(
        test_id="FAST_07",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Silencia el audio.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Mute rápido de audio.",
    ),
    RouterTestCase(
        test_id="FAST_08",
        category=TaskCategory.FAST_INTERACTION,
        prompt="¿Cómo estás hoy?",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Interacción de cortesía.",
    ),
    RouterTestCase(
        test_id="FAST_09",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Abre la calculadora.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Comando de herramienta simple.",
    ),
    RouterTestCase(
        test_id="FAST_10",
        category=TaskCategory.FAST_INTERACTION,
        prompt="Jessica, buenas tardes.",
        is_voice=True,
        expected_task_type=TaskCategory.FAST_INTERACTION,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Saludo vespertino.",
    ),

    # ── 2. TECHNICAL (10 casos) ───────────────────────────────────────────────
    RouterTestCase(
        test_id="TECH_01",
        category=TaskCategory.TECHNICAL,
        prompt="Analiza este error de Python: KeyError en dict al acceder a 'data'.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Error de clave en diccionario Python.",
    ),
    RouterTestCase(
        test_id="TECH_02",
        category=TaskCategory.TECHNICAL,
        prompt="Explícame este traceback de requests: ProviderConnectionError en localhost:11434.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Diagnóstico de excepción de red en HTTP.",
    ),
    RouterTestCase(
        test_id="TECH_03",
        category=TaskCategory.TECHNICAL,
        prompt="Revisa este código con posible race condition en un singleton de Python.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Concurrencia multihilo y sincronización con lock.",
    ),
    RouterTestCase(
        test_id="TECH_04",
        category=TaskCategory.TECHNICAL,
        prompt="¿Cómo solucionar un PermissionError al intentar escribir en C:\\Windows\\System32?",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Permisos del sistema de archivos en Windows.",
    ),
    RouterTestCase(
        test_id="TECH_05",
        category=TaskCategory.TECHNICAL,
        prompt="Explica cómo evitar un memory leak en Python al abrir archivos sin context manager.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Fugas de descriptores de archivo.",
    ),
    RouterTestCase(
        test_id="TECH_06",
        category=TaskCategory.TECHNICAL,
        prompt="Escribe una función segura con threading.RLock() para proteger un diccionario compartido.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Patrón de sincronización concurrente.",
    ),
    RouterTestCase(
        test_id="TECH_07",
        category=TaskCategory.TECHNICAL,
        prompt="Analiza este error de JSONDecodeError cuando el LLM devuelve markdown con ```json.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Parsing robusto con expresiones regulares.",
    ),
    RouterTestCase(
        test_id="TECH_08",
        category=TaskCategory.TECHNICAL,
        prompt="¿Cómo funciona el dunder __exit__ en un context manager de Python?",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Protocolo de context manager.",
    ),
    RouterTestCase(
        test_id="TECH_09",
        category=TaskCategory.TECHNICAL,
        prompt="Optimiza este algoritmo de desalojo LRU para modelos en VRAM con marcas de tiempo.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Estructura de datos y política de desalojo.",
    ),
    RouterTestCase(
        test_id="TECH_10",
        category=TaskCategory.TECHNICAL,
        prompt="Cómo capturar y clasificar una excepción ProviderTimeoutError en Python.",
        expected_task_type=TaskCategory.TECHNICAL,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "nvidia/nemotron-3-ultra-550b-a55b"),
        minimum_confidence=0.85,
        description="Manejo tipado de errores LLM.",
    ),

    # ── 3. COMPLEX REASONING (10 casos) ───────────────────────────────────────
    RouterTestCase(
        test_id="REASON_01",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza por qué el router está tomando decisiones contradictorias al alternar modelos.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Diagnóstico de coherencia lógica en enrutador.",
    ),
    RouterTestCase(
        test_id="REASON_02",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Diseña un plan para solucionar este problema de inconsistencia entre módulos.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Estrategia de resolución de conflictos de software.",
    ),
    RouterTestCase(
        test_id="REASON_03",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza varias causas posibles y propón una estrategia de balanceo entre modelos locales y remotos.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Análisis multi-variable y trade-offs.",
    ),
    RouterTestCase(
        test_id="REASON_04",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Explica la paradoja de Bayes y por qué una prueba con 99% de precisión tiene alta tasa de falsos positivos en enfermedades raras.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Lógica probabilística contra-intuitiva.",
    ),
    RouterTestCase(
        test_id="REASON_05",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza el trade-off arquitectónico entre latencia de red de 1.7s y precisión cognitiva en un asistente interactivo.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Compromiso entre latencia y capacidad.",
    ),
    RouterTestCase(
        test_id="REASON_06",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza el cuello de botella: GPU de 12GB con 1.5GB de Windows, si se cargan dos modelos de 5.5GB y 6.0GB.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Cálculo determinista de presupuesto de VRAM.",
    ),
    RouterTestCase(
        test_id="REASON_07",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Detecta la contradicción: sistema 100% offline que promete sincronización en tiempo real cada segundo en la nube.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Detección formal de contradicciones.",
    ),
    RouterTestCase(
        test_id="REASON_08",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza cómo resolver dependencias cruzadas entre tareas A, B, C y D en un pipeline.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Topología de dependencias y camino crítico.",
    ),
    RouterTestCase(
        test_id="REASON_09",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Por qué un script de Windows que devuelve 0 puede ser un falso éxito y qué probes de verificación se requieren.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Verificación de estado vs retorno de proceso.",
    ),
    RouterTestCase(
        test_id="REASON_10",
        category=TaskCategory.COMPLEX_REASONING,
        prompt="Analiza las decisiones contradictorias entre dos herramientas cuando una dice éxito y el proceso está cerrado.",
        expected_task_type=TaskCategory.COMPLEX_REASONING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Resolución de discrepancias con evidencia observable.",
    ),

    # ── 4. AGENT PLANNING (10 casos) ──────────────────────────────────────────
    RouterTestCase(
        test_id="PLAN_01",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Realiza estos cinco pasos y verifica cada uno antes de continuar al siguiente.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Plan secuencial de 5 etapas con checkpoints.",
    ),
    RouterTestCase(
        test_id="PLAN_02",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Investiga el problema, analiza los archivos y propón una solución estructurada paso a paso.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Plan de auditoría e investigación autónoma.",
    ),
    RouterTestCase(
        test_id="PLAN_03",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Planifica cómo solucionar este error y valida cada etapa aislando planificación de ejecución.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Separación de REASONING -> PLAN -> VERIFICATION.",
    ),
    RouterTestCase(
        test_id="PLAN_04",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Organiza los archivos de la carpeta Descargas en subcarpetas por extensión de forma atómica.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Plan de reestructuración de archivos con rollback.",
    ),
    RouterTestCase(
        test_id="PLAN_05",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Busca el archivo ventas.xlsx, cópialo a D:\\Backup y verifica que el tamaño y hash coincidan.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Copia y verificación de integridad.",
    ),
    RouterTestCase(
        test_id="PLAN_06",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Abre Google, busca la RTX 3060 y dime qué encontraste con un resumen en 3 puntos.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Búsqueda web, extracción y síntesis secuencial.",
    ),
    RouterTestCase(
        test_id="PLAN_07",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Primero abre el bloc de notas y después escribe un pequeño resumen de lo que acabamos de hablar.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Secuencia de dependencia de ventana y escritura.",
    ),
    RouterTestCase(
        test_id="PLAN_08",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Toma una captura de pantalla y guárdala en el escritorio con el nombre reporte.png validando que exista.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Captura y persistencia con verificación.",
    ),
    RouterTestCase(
        test_id="PLAN_09",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Crea una carpeta llamada Proyectos y mueve allí el archivo notas.txt asegurando no duplicar.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Manipulación segura de directorios.",
    ),
    RouterTestCase(
        test_id="PLAN_10",
        category=TaskCategory.AGENT_PLANNING,
        prompt="Diseña un plan para solucionar un fallo parcial al mover 5 archivos donde 2 arrojaron error.",
        expected_task_type=TaskCategory.AGENT_PLANNING,
        expected_model_family="nemotron",
        acceptable_models=("nvidia/nemotron-3-ultra-550b-a55b", "qwen3:8b"),
        minimum_confidence=0.85,
        description="Estrategia de compensación y rollback.",
    ),

    # ── 5. OFFLINE (5 casos) ──────────────────────────────────────────────────
    RouterTestCase(
        test_id="OFFLINE_01",
        category=TaskCategory.OFFLINE,
        prompt="Analiza este código de Python mientras no hay internet.",
        is_offline=True,
        expected_task_type=TaskCategory.OFFLINE,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "gemma4:e4b"),
        minimum_confidence=0.85,
        description="Tarea técnica sin conexión: debe usar modelo local.",
    ),
    RouterTestCase(
        test_id="OFFLINE_02",
        category=TaskCategory.OFFLINE,
        prompt="Abre el bloc de notas sin conexión.",
        is_offline=True,
        expected_task_type=TaskCategory.OFFLINE,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Comando local sin conexión.",
    ),
    RouterTestCase(
        test_id="OFFLINE_03",
        category=TaskCategory.OFFLINE,
        prompt="Explica este error de sintaxis en modo offline.",
        is_offline=True,
        expected_task_type=TaskCategory.OFFLINE,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "gemma4:e4b"),
        minimum_confidence=0.85,
        description="Explicación técnica desconectado.",
    ),
    RouterTestCase(
        test_id="OFFLINE_04",
        category=TaskCategory.OFFLINE,
        prompt="Planifica la organización de archivos locales desconectado de la red.",
        is_offline=True,
        expected_task_type=TaskCategory.OFFLINE,
        expected_model_family="qwen",
        acceptable_models=("qwen3:8b", "gemma4:e4b"),
        minimum_confidence=0.85,
        description="Planificación local en máquina.",
    ),
    RouterTestCase(
        test_id="OFFLINE_05",
        category=TaskCategory.OFFLINE,
        prompt="¿Qué hora es en el reloj del sistema sin internet?",
        is_offline=True,
        expected_task_type=TaskCategory.OFFLINE,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b",),
        minimum_confidence=0.85,
        description="Consulta directa offline.",
    ),

    # ── 6. AMBIGUOUS (5 casos) ────────────────────────────────────────────────
    RouterTestCase(
        test_id="AMBIG_01",
        category=TaskCategory.AMBIGUOUS,
        prompt="Abre el navegador.",
        expected_task_type=TaskCategory.AMBIGUOUS,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b", "qwen3:8b"),
        minimum_confidence=0.80,
        description="Solicitud sin navegador específico.",
    ),
    RouterTestCase(
        test_id="AMBIG_02",
        category=TaskCategory.AMBIGUOUS,
        prompt="Quiero hablar con alguien por WhatsApp.",
        expected_task_type=TaskCategory.AMBIGUOUS,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b", "qwen3:8b"),
        minimum_confidence=0.80,
        description="Falta destinatario en orden de mensajería.",
    ),
    RouterTestCase(
        test_id="AMBIG_03",
        category=TaskCategory.AMBIGUOUS,
        prompt="Ponme Google.",
        expected_task_type=TaskCategory.AMBIGUOUS,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b", "qwen3:8b"),
        minimum_confidence=0.80,
        description="Comando coloquial ambiguo entre abrir y buscar.",
    ),
    RouterTestCase(
        test_id="AMBIG_04",
        category=TaskCategory.AMBIGUOUS,
        prompt="Cierra eso.",
        expected_task_type=TaskCategory.AMBIGUOUS,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b", "qwen3:8b"),
        minimum_confidence=0.80,
        description="Deíctico sin foco claro.",
    ),
    RouterTestCase(
        test_id="AMBIG_05",
        category=TaskCategory.AMBIGUOUS,
        prompt="Hazlo ahora.",
        expected_task_type=TaskCategory.AMBIGUOUS,
        expected_model_family="gemma",
        acceptable_models=("gemma4:e4b", "qwen3:8b"),
        minimum_confidence=0.80,
        description="Verbo comodín sin objeto ni acción específica.",
    ),
)
